---
title: 'Amazon Redshift - Fundamentals'
subject: 'Amazon Redshift'
author:
- Jef Claes
keywords: ebooks, pandoc, pdf, html
rights: MIT License 
language: en-US
lang: en
cover-image: "cover.png"
tags: [pandoc, pdf, epub, mobi creation]
...
